### ISSUE TITLE
Docker needs to export Port, so the external client can connect to the running EVA server.

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/eva#112]
Docker needs to start EVA server and export the port. @jiashenC

**Comment by xzdandy** [comment]
> Which port do you want?

Is that configurable? The current port in eva.yml is 5432

**Comment by jiashenC** [comment]
I see. Then I can take that as input for my docker config file.

**Comment by xzdandy** [comment]
@jiashenC Is that better to export when you run the docker command? docker -p port:port
