### ISSUE TITLE
Some labels are marked as N/A why?

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/eva#114]
As an initial step for cost-based optimizer, I want to add SSD model along with FasterRCNN.

I wonder why some labels are marked as N/A for FasterRCNN like [here](https://github.com/georgia-tech-db/eva/blob/9010f4aa560422a472f0bc331bfad8a306c874b1/src/udfs/fastrcnn_object_detector.py#L63)?

**Comment by xzdandy** [comment]
@jiashenC https://pytorch.org/docs/stable/torchvision/models.html#object-detection-instance-segmentation-and-person-keypoint-detection

**Comment by jiashenC** [comment]
Interesting. So COCO has 81 classes including background. What is 91 classes? And the model is defined to be 91 classes, 10 of those are actually not used (return N/A).
