### ISSUE TITLE
Documentation Bug: src.storage.__init__.py executes code

### ISSUE THREAD

**Issue by Abdullahshah** [georgia-tech-db/eva#116]
The file `src/storage/__init__.py` executes code when creating a storage object. This causes problems with the documentation engine as it builds itself by importing each package (from the `__init__.py` files). This also causes some problems when building the documentation for some of the `src/executor/` files such as `plan_executor.py` and `storage_executor` as those import the `storage` package as well.

Currently, the documentation is skipping over this sub-directory but we discussed in the weekly meeting a potential quick fix to move the code out of this init file to `abstract_storage_engine.py` and `petastorm_storage_engine.py`

**Comment by Abdullahshah** [comment]
#100

**Comment by xzdandy** [comment]
Move StorageEngine outof the __init__.py in f914c47

**Comment by xzdandy** [comment]
- [ ] Make the new documentation online
