### ISSUE TITLE
Different UDF output format

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/eva#119]
The format of current master branch UDF output, `eva-reuse` and my SSD object detector is different. Need a sync format.

**Comment by gaurav274** [comment]
We will go with your SSD object detector format. Probably that should be most generic one.

**Comment by jiashenC** [comment]
Also the [bounding box format](https://github.com/georgia-tech-db/eva/blob/9010f4aa560422a472f0bc331bfad8a306c874b1/src/udfs/fastrcnn_object_detector.py#L95).

**Comment by gaurav274** [comment]
#316
