### ISSUE TITLE
Faster RCNN crash due to no object detected

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/eva#120]
Not really an urgent bug. Just keep a note here.

Index out of range error when the faster rcnn model does not detect any object [here](https://github.com/georgia-tech-db/eva/blob/9010f4aa560422a472f0bc331bfad8a306c874b1/src/udfs/fastrcnn_object_detector.py#L102).

**Comment by gaurav274** [comment]
Fixed!
