### ISSUE TITLE
Query Template for Filters

### ISSUE THREAD

**Issue by RodrigoDLPontes** [georgia-tech-db/eva#137]
The purpose of this issue is to discuss how filters (i.e. specialized NNs used as stand-ins for more expensive object detection models, as described in papers like [NoScope](https://arxiv.org/abs/1703.02529) and [BlazeIt](https://arxiv.org/abs/1805.01046)) should fit into EVA's queries.

**Comment by jarulraj** [comment]
We are no longer planning to use filters.
