### ISSUE TITLE
Connection response on EVA server

### ISSUE THREAD

**Issue by pchunduri6** [georgia-tech-db/eva#157]
Currently, the EVA server and client do not provide explicit messages to indicate that the connection is successfully established. Add these messages to the server and the client code.

**Comment by xzdandy** [comment]
For the server, we can logging the connection. For the client (I assume it means command line client instead of db api), we can print out the message. Let me know if you think this is good enough.

**Comment by pchunduri6** [comment]
That should be good enough. Thanks for looking into it!
