### ISSUE TITLE
Human-readable messages from server

### ISSUE THREAD

**Issue by pchunduri6** [georgia-tech-db/eva#158]
Right now, when the client issues a command, the server does not provide a human-readable response to the request. This affects the useability of the system. We need to add request-dependent messages to the response.

1. Connection established - Messages on server and client when a connection is established.
2. Upload - Message on the server with size and name of video being uploaded. Message on the client with the size of the video uploaded.

**Comment by xzdandy** [comment]
Shall we prepare a page or doc that indicates the response we want for every command, then we can start working on them.

**Comment by pchunduri6** [comment]
> Shall we prepare a page or doc that indicates the response we want for every command, then we can start working on them.

Sure, let's do that.
