### ISSUE TITLE
Incompatibility of eva environment with Jupyter notebook 

### ISSUE THREAD

**Issue by pchunduri6** [georgia-tech-db/eva#159]
In the current conda environment of Eva, the db_abi `connect` method fails (with an asyncio error) when run from a jupyter notebook. This issue only arises on the Eva environment and not in a fresh conda environment. Possible fixes include upgrading the python version, checking for package conflicts etc.

**Comment by jarulraj** [comment]
We no longer support `conda`. Is this resolved now?

**Comment by janzheng** [comment]
I'm getting this issue with the Colab notebooks — for some reason this worked about an hour ago, but now failing to connect?
