### ISSUE TITLE
Disallow multiple queries on the same cursor to ensure cursor correctness

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/eva#160]
We shouldn't allow concurrent select queries on the same cursor to ensure correctness.

`cursor.execute('query1')`
`cursor.execute('query2')`

The above code shouldn't be allowed. The user has to clear the cursor buffer before running the second query. Throw the following error. 
`InternalError: Unread result found`

**Comment by xzdandy** [comment]
Will do

**Comment by gaurav274** [comment]
#171
