### ISSUE TITLE
Upload fails when using with python notebook

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/eva#162]
Steps to reproduce:
1. Checkout the tutorial branch or PR #161 
2. Start EVA server and jupyter notebook on ada1. 
3. Run the `object_detection` notebook (specifically the upload cell)
4. Cmd fails with the following error.
 `[Errno 13] Permission denied: '/tmp/test_video.mp4'`

**Comment by pchunduri6** [comment]
The `permission denied` error occurs when a user tries to overwrite a file created by another user in the `/tmp` directory. In this case, changing the file name should resolve the issue.
