### ISSUE TITLE
FutureWarning: pyarrow.localfs is deprecated as of 2.0.0

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/eva#188]
`Pip` automatically installs latest `pyarrow` library, in which some functions are deprecated. 

To suppress those warnings, users can migrate to older `pyarrow` version.

**Comment by jiashenC** [comment]
I only tried two versions. `2.0.0` no warning. `5.0.0` warning. 

`2.0.0` works fine with the client but I did try running all unit tests.

**Comment by gaurav274** [comment]
We got rid of Pyspark and Petastorm.
