### ISSUE TITLE
Python 3.8.2 doesn't work when "LOAD DATA INFILE"

### ISSUE THREAD

**Issue by Shiyao-monster** [georgia-tech-db/eva#230]
Python 3.8.2 doesn't work when  I try "LOAD DATA INFILE 'test_video.mp4' INTO MyVideo;"
The eva_server shows the error is "ERROR FileFormatWrite: Job job_202......"
Lost task 0.0 in stage 2.0

<img width="681" alt="eva python issue" src="https://user-images.githubusercontent.com/61948834/156611630-e4c0555e-1890-460c-8fae-7d2bc5357a8a.png">

**Comment by xzdandy** [comment]
Please try manually cleaning the directory .eva/eva_datesets/
