### ISSUE TITLE
Clean the anlr4 parser definition 

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/eva#264]
File: [evaql_parser.g4](https://github.com/georgia-tech-db/eva/blob/master/eva/parser/evaql/evaql_parser.g4)

**Comment by jarulraj** [comment]
Ambiguity in parsing seems to be inevitable -- https://javadoc.io/doc/org.antlr/antlr4-runtime/4.0/org/antlr/v4/runtime/ANTLRErrorListener.html#reportAttemptingFullContext(org.antlr.v4.runtime.Parser,%20org.antlr.v4.runtime.dfa.DFA,%20int,%20int,%20org.antlr.v4.runtime.atn.ATNConfigSet)
