### ISSUE TITLE
Unable to run UPLOAD queries

### ISSUE THREAD

**Issue by Aryan-Rajoria** [georgia-tech-db/eva#347]
Unable to run the query `UPLOAD INFILE "../data/ua_detrac/ua_detrac.mp4" PATH "video.mp4";` 
I am trying to run the `object_detection` notebook in the tutorials.

## Expected
```
Response Object:
@status: 0
@batch: Batch Object:
@dataframe: Empty DataFrame
Columns: []
Index: []
@batch_size: 0
@identifier_column: id
@metrics: None
```
## Result
```
@status: -1
@batch: None
@error: ERROR: Syntax error - Line1: Col 2215458 - no viable alternative at input 'UPLOAD PATH 'ua_detrac.mp4' ........
```
complete [response.txt](https://github.com/georgia-tech-db/eva/files/9484274/error.txt)

## Reproduce
new install of EVA, following the steps in the `README` in a docker container with `ubuntu 18.04`, and then running `object_detection.ipynb`.

Furthermore, I receive the same error when running the query using the `eva_client`.

## Additional Context
I have verified my installation by running the `test.sh` script in `script/test/test.sh` with the following result:
![image](https://user-images.githubusercontent.com/57455619/188304139-321fcf8b-eb4a-4fcb-a05f-7056f192e6a3.png)

**Comment by xzdandy** [comment]
UPLOAD INFILE 'data/ua_detrac/ua_detrac.mp4' INTO MyVideo;

The readme is outdated. A PR fixed it but not merged yet.

**Comment by Aryan-Rajoria** [comment]
Facing similar problem in Running UDFs 
```
SELECT id, FastRCNNObjectDetector(data) FROM MyVideo;
```
returns a dataframe with empty rows.
