### ISSUE TITLE
Frame Accurate Seeking

### ISSUE THREAD

**Issue by BrianPugh** [georgia-tech-db/eva#414]
[OpenCV's video reader suffers from an issue](https://github.com/opencv/opencv/issues/9053) where frames after setting `CAP_PROP_POS_FRAMES` might either be invalid, or inaccurate (e.g. seeking to frame 1022 might actually seek to frame 1005). For some projects, this might not be a huge deal, but for projects that need to be synchronized with other data, this could be a huge silent bug.

While not a complete solution (I'm not too familiar with EVA's codebase), linked below is an easy-to-use, frame-accurate video reader using PyAV. PyAV has ffmpeg builtin, so it doesn't add any additional external non-python dependencies that could complicate installation. Its (mostly) a drop in for the opencv reader.

https://gist.github.com/BrianPugh/8de1a6f124516ec2a2a61caadcdf039a

Unrelated self-promotion: For managing your different readers, storage-backends, etc; consider checking out my [AutoRegistry](https://github.com/BrianPugh/autoregistry) project. Basically if your abstract base classes inherit from `Registry` instead of `ABC/ABCMeta`, child classes can be easily accessed via strings (from a config file, or other).

**Comment by gaurav274** [comment]
@BrianPugh Nice catch! Thanks for raising the issue. We are aware of the incorrect frame seeking in OpenCV. Based on our prior discussions, I recall we found another library [decord](https://github.com/dmlc/decord) that provides an accurate frame seeking out of the box. However, we did not change the storage engine as we were considering moving to a `time-based` seeking instead of `frame based.` IMO, time-based seeking seems intuitive to use in queries compared to frame-based. However, we might have to support both. 

Anyways, for frame-based seeking, OpenCV has to go. `PyAV`solution looks neat and can easily replace OpenCV. I guess it boils down to performance metrics and stable support. 
 
`AutoRgistry` sounds interesting. I'll check it out and consider the possibility of using it in `eva`.

**Comment by jarulraj** [comment]
@dungnmaster Is this issue fixed with our `decord` based reader?

**Comment by dungnmaster** [comment]
@jarulraj This should be fixed with the decord based reader but we are currently using it only for IFRAMES based queries. Should be a small change to switch every query to decord reader.

**Comment by petered** [comment]
Just a heads up - the seek of 
https://gist.github.com/BrianPugh/8de1a6f124516ec2a2a61caadcdf039a
Isn't frame-accurate for me (sometimes 1 frame off, sometimes more). 

My test is to basically scan through the video linearly, pick some frame (e.g. 5732), seek to it by reading frames sequentially (very slow), then start a new video player, try reading frames offset around that frame with seek (5722 - 5742), take the correlation with each of the offset frames to the original, and verify that the one offset 0 has correlation near 1, and the other offsets don't. 

From what I can tell the only thing on the market that seeks correctly is [Decord](https://github.com/dmlc/decord), but it produces a huge, huge memory leak (quickly crashing the machine on larger videos).   

Here's the gist of the file I'm using, based on pyav which does accurate frame-seeks.  No, it's not standalone, has some minor dependencies from my code, but they're easy to remove if you want it.  It launches in indexing worker on another process to linearly scan through and index the video.  
https://gist.github.com/petered/aa2b07ac8f38e638f63fae0ae838bc1f 

If anyone knows of a simple, clean, python library that performs the simple task of quickly, accurately, seeking to a frame at a given index without eating up all the memory on your machine - please do post it here!

**Comment by BrianPugh** [comment]
FWIW, I think we also noticed the solution I posted in 2022 wasn't frame accurate. At my company, we just read every frame start-to-end to guarantee synchronization. It's a bit inefficient, but we've adjusted our workflow around it.
