### ISSUE TITLE
Bug: Fix Github language breakdown

### ISSUE THREAD

**Issue by LordDarkula** [georgia-tech-db/eva#417]
Github is reporting that our code base is mostly jupyter, which might be misleading to people as EVA is a Python library

**Comment by gaurav274** [comment]
@LordDarkula Adding a `.gitattributes` file should fix the problem. Looks like GitHub uses file size to decide the percentage. 
https://github.com/github/linguist/blob/97bc889ce840208652bf09b45f3b7859de43fe8e/docs/overrides.md

**Comment by jarulraj** [comment]
Resolved in #433.
