### ISSUE TITLE
Code inconsistency 

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/eva#456]
@xzdandy What happens if the table already exists? This raised an issue that I did not notice before. I was using if_not_exists in the [load executor](https://github.com/georgia-tech-db/eva/blob/b8cfc51259cadc68b184b4ae2ef6da077cdcde6f/eva/executor/load_video_executor.py#L59). In [mat executor](https://github.com/georgia-tech-db/eva/blob/b8cfc51259cadc68b184b4ae2ef6da077cdcde6f/eva/executor/create_mat_view_executor.py#L34), we can use handle_if_not_exists because the catalog entry is created in the mat executor. But this is not the case for the load operator, the catalog entry is created before the load executor. I think we shall choose one way for both of them. And update the mat, load design, and this creates (e.g., doc what happens the table exists, remove **kwargs, add a call to check whether a table exists or can we use read to do it?)

**Comment by xzdandy** [comment]
After discussed with Gaurav, we will move the load binder logic into the executor.
