### ISSUE TITLE
"OverflowError: Maximum recursion level reached" when executing a load CSV command

### ISSUE THREAD

**Issue by Anirudh58** [georgia-tech-db/eva#470]
Command to be executed: 

`LOAD FILE 'bddtest/info/bddtest_00a2e3ca5c856cde.csv' INTO bddtestmeta WITH FORMAT CSV;`

Error snapshot: 
![image](https://user-images.githubusercontent.com/11812968/199637350-9f341862-ddd8-4890-8cc4-cf05fe901a64.png)

**Comment by jarulraj** [comment]
Resolved in #647
