### ISSUE TITLE
Accessing a Table after restarting eva_server leads to error

### ISSUE THREAD

**Issue by Aryan-Rajoria** [georgia-tech-db/eva#542]
Running the command
`SELECT * FROM v2`
results in error
```
@status: ResponseStatus.FAIL
@batch: 
 None
@error: '/root/.eva/0.1.3+dev/eva_datasets/b9093a36e5741249f73b2dfd00a7c8e6'
```

Steps to reporduce:
1) Create a table and add some images to it
2) restart `eva_server`
3) will get the above error

**Comment by gaurav274** [comment]
Fixed with #543
