### ISSUE TITLE
Remove unnecessary code from insert/delete executor

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/eva#594]
1. https://github.com/georgia-tech-db/eva/blob/2212d6cdcb1341ab55e4675da1b392c41d5160c7/eva/executor/insert_executor.py#L77
PR: https://github.com/georgia-tech-db/eva/commit/86825d39a5ba8b4cd83daa81727e8cb340d9cc6a

**Comment by jarulraj** [comment]
Resolved in #611
