### ISSUE TITLE
tests get stuck on `intel-macos` 

### ISSUE THREAD

**Issue by suryatejreddy** [georgia-tech-db/eva#661]
[Link to circleci build](https://app.circleci.com/pipelines/github/georgia-tech-db/eva/3204/workflows/715108e7-9679-428b-975d-baaf9642c696/jobs/12166)
[Link to build with increased timeout](https://app.circleci.com/pipelines/github/georgia-tech-db/eva/3205/workflows/ab006bb8-05b6-4a3b-85e9-701e896cef3d/jobs/12174)

**Comment by jarulraj** [comment]
@gaurav274 Can we close this issue now that the build works on macos?
