### ISSUE TITLE
Duplicate Image Error

### ISSUE THREAD

**Issue by aryan-rajoria** [georgia-tech-db/eva#662]
This issue is encountered when loading many images to EVA (having different files names).

In the `_xform_file_url_to_file_name()` function in `abstract_media_storage_engine` we use:
```python
zlib.adler32(str(i).encode("utf-8")) & 0xFFFFFFFF
```
sometimes different file names have the same hash which creates this issue.

**Comment by jiashenC** [comment]
#658

**Comment by jiashenC** [comment]
Fixed in https://github.com/georgia-tech-db/eva/pull/712. Reopen if new issue appears.
