### ISSUE TITLE
ReuseTest has unexpectedly high memory usage

### ISSUE THREAD

**Issue by dungnmaster** [georgia-tech-db/eva#688]
The integration tests that were added as a part of the caching feature were leading to higher-than-normal memory usage. The specific usage in this case crossed the 8GB threshold which is the memory assigned to test containers in CI. This was causing the test suite execution to be killed before completion.

From some initial investigations, we pinpointed the root cause of this to be the failure of the garbage collector to remove the redundant instances of the yolov5 model on its own between different queries of the same test case. The presence of this redundant instance was spiking up memory usage. 

As a current fix, we are manually invoking the garbage collector between the queries in these tests which has brought down the memory usage to its normal value.

cc: @gaurav274

**Comment by gaurav274** [comment]
Closing as it is an issue with yolo model. For now, we explicitly call garbage collector to remove yolo from memory.
