### ISSUE TITLE
CSV table is not being dropped

### ISSUE THREAD

**Issue by jarulraj** [georgia-tech-db/eva#709]
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### EVA DB Component

Data Loader

### Bug

In the `test_toxicity_classification` test, the data is not being loaded with a table  error

Running this test twice will help reproduce the problem:
1. `pytest -k 'test_toxicity_classification' -s -v`  
2. `pytest -k 'test_toxicity_classification' -s -v`  

<img width="1140" alt="bug" src="https://user-images.githubusercontent.com/5521975/236728274-2394a4bd-2a60-42d9-818b-5fdb00f05d29.png">

### Environment

- EVA DB: 0.2.2+dev

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jarulraj** [comment]
This is likely because the Drop Executor is not correctly identifying that the table `MyCSV` already exists.

`DROP TABLE IF EXISTS MyCSV;`

However, in the next call, the create table executor does find that the table exists.

`CREATE TABLE MyCSV ...`

**Comment by gaurav274** [comment]
I found a similar issue and fixed it via https://github.com/georgia-tech-db/eva/pull/706.

**Comment by jarulraj** [comment]
It had to do with the MyCSV table not being dropped in teardown.
