### ISSUE TITLE
Queries stuck at eva server waiting for async results (M1 mac)

### ISSUE THREAD

**Issue by yulaicui** [georgia-tech-db/eva#722]
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### EVA DB Component

Integrations

### Bug

eva server stuck at simple query 

`cursor.execute("LOAD VIDEO '../data/mnist/mnist.mp4' INTO MNISTVid")
response = cursor.fetch_all()
response.as_df()`

### Environment

- EVA DB: v0.2.2
- OS: Mac OS
- Python: 3.9.7

### Minimal Reproducible Example

1. clone eva db
2. create virtual environment with 
`python3 -m venv test_eva_db`
`source test_eva_db/bin/activate`
`pip install --upgrade pip`
`pip install -e ".[dev]" `
`pip install .`
3. run server with `eva_server`
4. on a separate terminal, run the simple query on jupyter notebook

### Additional

@Jo

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
@jarulraj @xzdandy What is the issue here?

**Comment by jarulraj** [comment]
Can check the server log -- `eva.log` -- to see if it is still running?

**Comment by yulaicui** [comment]
> 1. Can check the server log -- `eva.log` -- to see if the server is still running?
> 2. Are you able to run queries using the `eva_client` (terminal client instead of Jupyter notebook)?

1. yes. the server is still running
2. eva_client gives the same problem. I ran a very simply query 'DROP TABLE IF EXISTS MNISTVid' which should not drop anything because the table doesn't exist, and it stuck there forever. 

this problem could be specific to M1. Is anyone using M1/M2 able to recreate this issue?

**Comment by yulaicui** [comment]
issue resolved. turns out the new version enforces that all queries should end with a semicolon while previous versions don't. We should check on previous notebooks and see if this enforcement is carried out in old examples
