### ISSUE TITLE
tutorials/01-mnist.ipynb fails on circle ci

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/eva#782]
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### EVA DB Component

Integrations

### Bug

It seems that tutorials/01-mnist.ipynb fails on circle ci after #780.

**Error Message:**
```
FAILED tutorials/01-mnist.ipynb:: - ExecutorError: Error creating UDF: Couldn't load UDF from /home/circleci/project/tutorials/eva_mnist_udf.py : [Errno 2] No such file or directory: '/home/circleci/project/tutorials/eva_mnist_udf.py'. Ensure that the file exists and that it is a valid Python file. 
```

### Minimal Reproducible Example

**Example circleci output:** 
https://circleci.com/api/v1.1/project/github/georgia-tech-db/eva/20552/output/104/0?file=true&allocation-id=647047b0849ff7344f9fd3cd-0-build%2F7666D827

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jarulraj** [comment]
I suspect that this is because the models are getting downloaded with the very first notebook. So, the server takes more than 10 seconds to start.
